apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: example-app
## Default profile for use with `skaffold dev`
build:
  tagPolicy:
    gitCommit:
      variant: CommitSha
      ignoreChanges: true
  artifacts:
    - image: stevenacoffman/small
      docker:
        dockerfile: ./Dockerfile
deploy:
  kustomize:
    paths:
      - k8s/overlays/local
  kubeContext: k3d-k3s-local
portForward:
  - resourceType: service
    resourceName: example-app
    namespace: default
    port: 3000
    localPort: 3000
profiles:
  - name: local
    deploy:
      kustomize:
        paths:
          - k8s/overlays/local
      kubeContext: k3d-k3s-local
    ## This profile runs unit tests and builds the image
  - name: test
    build:
      local:
        push: false
      artifacts:
      - image: stevenacoffman/small
        docker:
          dockerfile: ./Dockerfile
  - name: production
    ## This profile pushes the image
    build:
      local:
        push: true
    deploy:
      kustomize:
        paths:
          - k8s/overlays/production
      kubeContext: gke_khan-internal-services_us-central1-b_internal-services