apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: example-app
## Default profile for use with `skaffold dev`
build:
  artifacts:
    - image: registry.local:5000/example-app
      docker:
        dockerfile: ./Dockerfile
  insecureRegistries:
    - registry.local:5000
deploy:
  kustomize:
    paths:
      - k8s/overlays/local
  kubeContext: k3d-k3s-local
portForward:
  - resourceType: service
    resourceName: example-app
    namespace: default
    port: 3000
    localPort: 3000
profiles:
  - name: local
    deploy:
      kustomize:
        paths:
          - k8s/overlays/local
      kubeContext: k3d-k3s-local
  - name: test
    ## This profile runs unit tests and builds the image
    build:
      artifacts:
        - image: StevenACoffman/small
          docker:
            dockerfile: ./Dockerfile
      local:
        push: false
  - name: production
    ## This profile pushes the image
    build:
      artifacts:
        - image: StevenACoffman/small
          docker:
            dockerfile: ./Dockerfile
      local:
        push: true
